### ISSUE TITLE
All IPs are the same no matter what pc or IP I am on

### ISSUE THREAD

**Issue by skeppysdoglol** [yo-aiv1/thebear#2] opened 2024-09-28 03:53 UTC
I am not here if I should report this here or on the hidden cave git. When I run it on my pc, it works amazingly, firstly I want to say this project is amazing and you are very amazing at what you do. Anyways.. on to the problem. No matter what pc I run it on, it shows the same IP always, which is the pc localhost ip.. is this normal? Is there any way to seperate these logs between the pc? Because it just puts multiple browsers under 127.0.0.1. Thanks very much

**Comment by yo-aiv1** [comment] 2024-09-28 11:21
Hi, thank you for the report.
I think the problem is when the requests are coming from the same network where the hidden cave is deployed, for example if you deployed the hidden cave in your machine and used a VM in your same machine to test it then it will have the localhost ip.
could you please try it use it while deploying it on a machine outside of your network

**Comment by skeppysdoglol** [comment] 2024-09-28 19:38
I have hidden cave hosted on a totally different network overall. I have tried things like connecting my pc to a hotspot and testing on my laptop with a vpn but no matter what it still says 127.0.01 for everything and puts all the browsers under that one in hiddencave

**Comment by yo-aiv1** [comment] 2024-09-28 19:42
can you look in the storage.json if the IPs are all 127.0.0.1?

**Comment by yo-aiv1** [comment] 2024-09-28 19:54
I figure out what the problem is, im working on it

**Comment by yo-aiv1** [comment] 2024-09-28 22:11
@skeppysdoglol
i guess its fixed now, can you confirm that?

**Closed** 2024-09-29 01:20 UTC
